export type BasePos = "GK" | "DEF" | "MID" | "WING" | "ST";

export type CardTier = "legend" | "gold" | "silver" | "bronze";

export interface Player {
  id: string;
  nameAr: string;
  clubAr: string;
  nation: string;
  flag: string;
  league: string;
  base: BasePos;
  overall: number;
  value: number;
  tier: CardTier;
  image?: string;
}

export const PLAYER_IMAGES: Record<string, string> = {
  messi: "https://images.fotmob.com/image_resources/playerimages/30981.png",
  ronaldo: "https://images.fotmob.com/image_resources/playerimages/30893.png",
  mbappe: "https://images.fotmob.com/image_resources/playerimages/701154.png",
  haaland: "https://images.fotmob.com/image_resources/playerimages/737066.png",
  vini: "https://images.fotmob.com/image_resources/playerimages/846033.png",
  bellingham: "https://images.fotmob.com/image_resources/playerimages/1077894.png",
  salah: "https://images.fotmob.com/image_resources/playerimages/292462.png",
  debruyne: "https://images.fotmob.com/image_resources/playerimages/169200.png",
  kane: "https://images.fotmob.com/image_resources/playerimages/194165.png",
  lewa: "https://images.fotmob.com/image_resources/playerimages/93447.png",
  rodri: "https://images.fotmob.com/image_resources/playerimages/675088.png",
  valverde: "https://images.fotmob.com/image_resources/playerimages/743533.png",
  pedri: "https://images.fotmob.com/image_resources/playerimages/1083323.png",
  gavi: "https://images.fotmob.com/image_resources/playerimages/1279040.png",
  wirtz: "https://images.fotmob.com/image_resources/playerimages/1152455.png",
  musiala: "https://images.fotmob.com/image_resources/playerimages/1156141.png",
  odegaard: "https://images.fotmob.com/image_resources/playerimages/534670.png",
  kimmich: "https://images.fotmob.com/image_resources/playerimages/460632.png",
  modric: "https://images.fotmob.com/image_resources/playerimages/31097.png",
  fdj: "https://images.fotmob.com/image_resources/playerimages/638622.png",
  bruno: "https://images.fotmob.com/image_resources/playerimages/422685.png",
  saka: "https://images.fotmob.com/image_resources/playerimages/961995.png",
  foden: "https://images.fotmob.com/image_resources/playerimages/815006.png",
  rapha: "https://images.fotmob.com/image_resources/playerimages/696679.png",
  yamal: "https://images.fotmob.com/image_resources/playerimages/1467236.png",
  leao: "https://images.fotmob.com/image_resources/playerimages/848844.png",
  kvara: "https://images.fotmob.com/image_resources/playerimages/900433.png",
  doku: "https://images.fotmob.com/image_resources/playerimages/942368.png",
  nico: "https://images.fotmob.com/image_resources/playerimages/1202110.png",
  olise: "https://images.fotmob.com/image_resources/playerimages/1029063.png",
  dembele: "https://images.fotmob.com/image_resources/playerimages/692984.png",
  griez: "https://images.fotmob.com/image_resources/playerimages/184138.png",
  osimhen: "https://images.fotmob.com/image_resources/playerimages/687681.png",
  vlahovic: "https://images.fotmob.com/image_resources/playerimages/737857.png",
  gyokeres: "https://images.fotmob.com/image_resources/playerimages/664500.png",
  isak: "https://images.fotmob.com/image_resources/playerimages/690107.png",
  martinez_l: "https://images.fotmob.com/image_resources/playerimages/690230.png",
  nunez: "https://images.fotmob.com/image_resources/playerimages/950561.png",
  benzema: "https://images.fotmob.com/image_resources/playerimages/26166.png",
  mitrovic: "https://images.fotmob.com/image_resources/playerimages/351860.png",
  vandijk: "https://images.fotmob.com/image_resources/playerimages/209405.png",
  dias: "https://images.fotmob.com/image_resources/playerimages/614006.png",
  saliba: "https://images.fotmob.com/image_resources/playerimages/955406.png",
  saliba2: "https://images.fotmob.com/image_resources/playerimages/1358581.png",
  hernandez: "https://images.fotmob.com/image_resources/playerimages/724371.png",
  bastoni: "https://images.fotmob.com/image_resources/playerimages/805451.png",
  hakimi: "https://images.fotmob.com/image_resources/playerimages/770881.png",
  cubarsi: "https://images.fotmob.com/image_resources/playerimages/1532137.png",
  marquinhos: "https://images.fotmob.com/image_resources/playerimages/267365.png",
  rudiger: "https://images.fotmob.com/image_resources/playerimages/276738.png",
  carvajal: "https://images.fotmob.com/image_resources/playerimages/282674.png",
  taa: "https://images.fotmob.com/image_resources/playerimages/760712.png",
  gvardiol: "https://images.fotmob.com/image_resources/playerimages/1070712.png",
  militao: "https://images.fotmob.com/image_resources/playerimages/844415.png",
  kounde: "https://images.fotmob.com/image_resources/playerimages/705450.png",
  romero: "https://images.fotmob.com/image_resources/playerimages/789066.png",
  alba: "https://images.fotmob.com/image_resources/playerimages/150739.png",
  courtois: "https://images.fotmob.com/image_resources/playerimages/170323.png",
  alisson: "https://images.fotmob.com/image_resources/playerimages/319784.png",
  donnarumma: "https://images.fotmob.com/image_resources/playerimages/618878.png",
  neuer: "https://images.fotmob.com/image_resources/playerimages/27299.png",
  maignan: "https://images.fotmob.com/image_resources/playerimages/466439.png",
  raya: "https://images.fotmob.com/image_resources/playerimages/562727.png",
  oblak: "https://images.fotmob.com/image_resources/playerimages/177126.png",
  bounou: "https://images.fotmob.com/image_resources/playerimages/340020.png",
  elshenawy: "https://images.fotmob.com/image_resources/playerimages/546550.png",
  palmer: "https://images.fotmob.com/image_resources/playerimages/1096353.png",
  rice: "https://images.fotmob.com/image_resources/playerimages/654096.png",
  mainoo: "https://images.fotmob.com/image_resources/playerimages/1292810.png",
  zubimendi: "https://images.fotmob.com/image_resources/playerimages/1031325.png",
  tchouameni: "https://images.fotmob.com/image_resources/playerimages/914458.png",
  camavinga: "https://images.fotmob.com/image_resources/playerimages/1015185.png",
  barella: "https://images.fotmob.com/image_resources/playerimages/541820.png",
  szoboszlai: "https://images.fotmob.com/image_resources/playerimages/846005.png",
  mac_allister: "https://images.fotmob.com/image_resources/playerimages/831489.png",
  konate: "https://images.fotmob.com/image_resources/playerimages/820140.png",
  martinez_e: "https://images.fotmob.com/image_resources/playerimages/268375.png",
  sommer: "https://images.fotmob.com/image_resources/playerimages/41618.png",
  diogo: "https://images.fotmob.com/image_resources/playerimages/795630.png",
  huijsen: "https://images.fotmob.com/image_resources/playerimages/1367619.png",
  guehi: "https://images.fotmob.com/image_resources/playerimages/844425.png",
  dumfries: "https://images.fotmob.com/image_resources/playerimages/593118.png",
  theo2: "https://images.fotmob.com/image_resources/playerimages/724371.png",
  sesko: "https://images.fotmob.com/image_resources/playerimages/1073977.png",
  zirkzee: "https://images.fotmob.com/image_resources/playerimages/950830.png",
  retegui: "https://images.fotmob.com/image_resources/playerimages/905546.png",
  david: "https://images.fotmob.com/image_resources/playerimages/939569.png",
  openda: "https://images.fotmob.com/image_resources/playerimages/747767.png",
  marmoush: "https://images.fotmob.com/image_resources/playerimages/839204.png",
  kudus: "https://images.fotmob.com/image_resources/playerimages/891743.png",
  mudryk: "https://images.fotmob.com/image_resources/playerimages/976506.png",
  garnacho: "https://images.fotmob.com/image_resources/playerimages/1203665.png",
  rodrygo: "https://images.fotmob.com/image_resources/playerimages/895362.png",
  cherki: "https://images.fotmob.com/image_resources/playerimages/1104053.png",
  diaz_l: "https://images.fotmob.com/image_resources/playerimages/860914.png",
  nkunku: "https://images.fotmob.com/image_resources/playerimages/704523.png",
  ederson: "https://images.fotmob.com/image_resources/playerimages/363364.png",
  lunin: "https://images.fotmob.com/image_resources/playerimages/800882.png",
  onana: "https://images.fotmob.com/image_resources/playerimages/611491.png",
  mamardashvili: "https://images.fotmob.com/image_resources/playerimages/948800.png",
  vicario: "https://images.fotmob.com/image_resources/playerimages/538501.png",
  trubin: "https://images.fotmob.com/image_resources/playerimages/1022350.png",
  kobel: "https://images.fotmob.com/image_resources/playerimages/764018.png",
  nuno_mendes: "https://images.fotmob.com/image_resources/playerimages/1158945.png",
  van_de_ven: "https://images.fotmob.com/image_resources/playerimages/1097466.png",
  araujo: "https://images.fotmob.com/image_resources/playerimages/921253.png",
  kim_minjae: "https://images.fotmob.com/image_resources/playerimages/828159.png",
  upamecano: "https://images.fotmob.com/image_resources/playerimages/658554.png",
  calafiori: "https://images.fotmob.com/image_resources/playerimages/1105912.png",
  gabriel: "https://images.fotmob.com/image_resources/playerimages/795179.png",
  stones: "https://images.fotmob.com/image_resources/playerimages/263653.png",
  de_ligt: "https://images.fotmob.com/image_resources/playerimages/769895.png",
  bremer: "https://images.fotmob.com/image_resources/playerimages/857269.png",
  dimarco: "https://images.fotmob.com/image_resources/playerimages/605224.png",
  frattesi: "https://images.fotmob.com/image_resources/playerimages/815431.png",
  vitinha: "https://images.fotmob.com/image_resources/playerimages/1061249.png",
  joao_neves: "https://images.fotmob.com/image_resources/playerimages/1342757.png",
  enzo: "https://images.fotmob.com/image_resources/playerimages/1137705.png",
  caicedo: "https://images.fotmob.com/image_resources/playerimages/1137668.png",
  bernardo: "https://images.fotmob.com/image_resources/playerimages/488139.png",
  gundogan: "https://images.fotmob.com/image_resources/playerimages/178818.png",
  locatelli: "https://images.fotmob.com/image_resources/playerimages/624166.png",
  depaul: "https://images.fotmob.com/image_resources/playerimages/324578.png",
  xavi_simons: "https://images.fotmob.com/image_resources/playerimages/1173787.png",
  doue: "https://images.fotmob.com/image_resources/playerimages/1339208.png",
  barcola: "https://images.fotmob.com/image_resources/playerimages/1297165.png",
  kubo: "https://images.fotmob.com/image_resources/playerimages/848289.png",
  mitoma: "https://images.fotmob.com/image_resources/playerimages/862608.png",
  sancho: "https://images.fotmob.com/image_resources/playerimages/846381.png",
  coman: "https://images.fotmob.com/image_resources/playerimages/429265.png",
  chiesa: "https://images.fotmob.com/image_resources/playerimages/784510.png",
  savinho: "https://images.fotmob.com/image_resources/playerimages/1174337.png",
  julian: "https://images.fotmob.com/image_resources/playerimages/974753.png",
  thuram: "https://images.fotmob.com/image_resources/playerimages/621562.png",
  hojlund: "https://images.fotmob.com/image_resources/playerimages/1199272.png",
  boniface: "https://images.fotmob.com/image_resources/playerimages/1035208.png",
  watkins: "https://images.fotmob.com/image_resources/playerimages/540088.png",
  solanke: "https://images.fotmob.com/image_resources/playerimages/591734.png",
  endrick: "https://images.fotmob.com/image_resources/playerimages/1406729.png",
  duran: "https://images.fotmob.com/image_resources/playerimages/1088066.png",
  neymar: "https://images.fotmob.com/image_resources/playerimages/19533.png",
  hamdallah: "https://images.fotmob.com/image_resources/playerimages/422288.png",
  kanno: "https://images.fotmob.com/image_resources/playerimages/866373.png",
  alshehri: "https://images.fotmob.com/image_resources/playerimages/384407.png",
  trezeguet: "https://images.fotmob.com/image_resources/playerimages/513492.png",
  mostafa: "https://images.fotmob.com/image_resources/playerimages/817500.png",
  msakni: "https://images.fotmob.com/image_resources/playerimages/192134.png",
  bennasser: "https://images.fotmob.com/image_resources/playerimages/465617.png",
  bouali: "https://images.fotmob.com/image_resources/playerimages/535523.png",
  alowais: "https://images.fotmob.com/image_resources/playerimages/1125083.png",
  hamed: "https://images.fotmob.com/image_resources/playerimages/545890.png",
  hakim: "https://images.fotmob.com/image_resources/playerimages/360559.png",
  amrabat: "https://images.fotmob.com/image_resources/playerimages/593116.png",
  elneny: "https://images.fotmob.com/image_resources/playerimages/339992.png",
  hegazy: "https://images.fotmob.com/image_resources/playerimages/297556.png",
  marcelo: "https://images.fotmob.com/image_resources/playerimages/28467.png",
  dani: "https://images.fotmob.com/image_resources/playerimages/33988.png",
  akram: "https://images.fotmob.com/image_resources/playerimages/613792.png",
  moanes: "https://images.fotmob.com/image_resources/playerimages/289472.png",
  rookie_gk: "https://images.fotmob.com/image_resources/playerimages/1228546.png",
  rookie_def: "https://images.fotmob.com/image_resources/playerimages/670885.png",
  rookie_mid: "https://images.fotmob.com/image_resources/playerimages/307753.png",
  rookie_wing: "https://images.fotmob.com/image_resources/playerimages/278343.png",
  rookie_st: "https://images.fotmob.com/image_resources/playerimages/844226.png",
  buffon: "https://images.fotmob.com/image_resources/playerimages/30717.png",
  iniesta: "https://images.fotmob.com/image_resources/playerimages/30955.png",
  pirlo: "https://images.fotmob.com/image_resources/playerimages/30731.png",
  ramos: "https://images.fotmob.com/image_resources/playerimages/30962.png",
  ibra: "https://images.fotmob.com/image_resources/playerimages/35724.png",
  aguero: "https://images.fotmob.com/image_resources/playerimages/37412.png",
  robben: "https://images.fotmob.com/image_resources/playerimages/30834.png",
  ribery: "https://images.fotmob.com/image_resources/playerimages/30924.png",
  bale: "https://images.fotmob.com/image_resources/playerimages/31921.png",
  hazard: "https://images.fotmob.com/image_resources/playerimages/107417.png",
  terstegen: "https://images.fotmob.com/image_resources/playerimages/184554.png",
  elsulaya: "https://images.fotmob.com/image_resources/playerimages/640284.png",
  gerrard: "https://images.fotmob.com/image_resources/playerimages/30618.png",
  maradona: "https://images.fotmob.com/image_resources/playerimages/158546.png",
  nedved: "https://images.fotmob.com/image_resources/playerimages/30940.png",
  pele: "https://images.fotmob.com/image_resources/playerimages/163605.png",
  cruyff: "https://images.fotmob.com/image_resources/playerimages/30811.png",
  henry: "https://images.fotmob.com/image_resources/playerimages/30626.png",
  drogba: "https://images.fotmob.com/image_resources/playerimages/30822.png",
  puskas: "https://images.fotmob.com/image_resources/playerimages/30961.png",
  eusebio: "https://images.fotmob.com/image_resources/playerimages/30853.png",
  romario: "https://images.fotmob.com/image_resources/playerimages/30921.png",
  totti: "https://images.fotmob.com/image_resources/playerimages/30919.png",
  kaka: "https://images.fotmob.com/image_resources/playerimages/41044.png",
  scholes: "https://images.fotmob.com/image_resources/playerimages/30373.png",
  beckham: "https://images.fotmob.com/image_resources/playerimages/30892.png",
  roberto_carlos: "https://images.fotmob.com/image_resources/playerimages/30895.png",
  nesta: "https://images.fotmob.com/image_resources/playerimages/30941.png",
  puyol: "https://images.fotmob.com/image_resources/playerimages/30661.png",
  schmeichel: "https://images.fotmob.com/image_resources/playerimages/30948.png",
  yashin: "https://images.fotmob.com/image_resources/playerimages/30889.png",
  shevchenko: "https://images.fotmob.com/image_resources/playerimages/30947.png",
  raul: "https://images.fotmob.com/image_resources/playerimages/27038.png",
  kahn: "https://images.fotmob.com/image_resources/playerimages/30879.png",
  figo: "https://images.fotmob.com/image_resources/playerimages/30696.png",
  cannavaro: "https://images.fotmob.com/image_resources/playerimages/34520.png",
  maldini: "https://images.fotmob.com/image_resources/playerimages/26555.png",
  beckenbauer: "https://images.fotmob.com/image_resources/playerimages/30827.png",
  zico: "https://images.fotmob.com/image_resources/playerimages/30977.png",
  baggio: "https://images.fotmob.com/image_resources/playerimages/30820.png",
  r9: "https://images.fotmob.com/image_resources/playerimages/30900.png",
  ronaldinho: "https://images.fotmob.com/image_resources/playerimages/30743.png",
  zidane: "https://images.fotmob.com/image_resources/playerimages/715485.png",
  xavi: "https://images.fotmob.com/image_resources/playerimages/39854.png",
  casillas: "https://images.fotmob.com/image_resources/playerimages/30657.png",
  saadoun: "https://images.fotmob.com/image_resources/playerimages/614006.png",
  taha: "https://images.fotmob.com/image_resources/playerimages/770881.png",
  fahd: "https://images.fotmob.com/image_resources/playerimages/307753.png",
  hamada: "https://images.fotmob.com/image_resources/playerimages/675088.png",
  hares: "https://images.fotmob.com/image_resources/playerimages/562727.png",
  sobhy: "https://images.fotmob.com/image_resources/playerimages/562727.png",
  waleed: "https://images.fotmob.com/image_resources/playerimages/278343.png",
  nabil: "https://images.fotmob.com/image_resources/playerimages/278343.png",
  ashraf: "https://images.fotmob.com/image_resources/playerimages/844226.png",
  abolamba: "https://images.fotmob.com/image_resources/playerimages/844226.png",
  reserve_gk: "https://images.fotmob.com/image_resources/playerimages/562727.png",
  reserve_def: "https://images.fotmob.com/image_resources/playerimages/614006.png",
  reserve_mid: "https://images.fotmob.com/image_resources/playerimages/307753.png",
  reserve_wing: "https://images.fotmob.com/image_resources/playerimages/278343.png",
  reserve_st: "https://images.fotmob.com/image_resources/playerimages/844226.png",
};

export function getPlayerImage(player?: { id?: string; nameAr?: string; image?: string } | null): string | undefined {
  if (!player?.id) return undefined;
  return player.image || PLAYER_IMAGES[player.id];
}

function tierOf(ovr: number): CardTier {
  if (ovr >= 96) return "legend";
  if (ovr >= 85) return "gold";
  if (ovr >= 78) return "silver";
  return "bronze";
}

type Row = [string, string, string, string, string, BasePos, number, number];

const ROWS: Row[] = [
  // id, nameAr, clubAr, nation, flag, base, ovr, value
  ["messi", "ليونيل ميسي", "إنتر ميامي", "الأرجنتين", "🇦🇷", "WING", 94, 60],
  ["ronaldo", "كريستيانو رونالدو", "النصر", "البرتغال", "🇵🇹", "ST", 93, 50],
  ["mbappe", "كيليان مبابي", "ريال مدريد", "فرنسا", "🇫🇷", "ST", 93, 180],
  ["haaland", "إيرلينغ هالاند", "مانشستر سيتي", "النرويج", "🇳🇴", "ST", 93, 175],
  ["vini", "فينيسيوس جونيور", "ريال مدريد", "البرازيل", "🇧🇷", "WING", 92, 170],
  ["bellingham", "جود بيلينغهام", "ريال مدريد", "إنجلترا", "🏴", "MID", 91, 165],
  ["salah", "محمد صلاح", "ليفربول", "مصر", "🇪🇬", "WING", 91, 70],
  ["debruyne", "كيفن دي بروين", "مانشستر سيتي", "بلجيكا", "🇧🇪", "MID", 91, 55],
  ["kane", "هاري كين", "بايرن ميونخ", "إنجلترا", "🏴", "ST", 91, 90],
  ["lewa", "روبرت ليفاندوفسكي", "برشلونة", "بولندا", "🇵🇱", "ST", 89, 45],
  ["rodri", "رودري", "مانشستر سيتي", "إسبانيا", "🇪🇸", "MID", 91, 120],
  ["valverde", "فيدي فالفيردي", "ريال مدريد", "أوروغواي", "🇺🇾", "MID", 89, 120],
  ["pedri", "بيدري", "برشلونة", "إسبانيا", "🇪🇸", "MID", 88, 100],
  ["gavi", "غافي", "برشلونة", "إسبانيا", "🇪🇸", "MID", 85, 80],
  ["wirtz", "فلوريان فيرتز", "ليفربول", "ألمانيا", "🇩🇪", "MID", 89, 130],
  ["musiala", "جمال موسيالا", "بايرن ميونخ", "ألمانيا", "🇩🇪", "MID", 89, 140],
  ["odegaard", "مارتن أوديغارد", "أرسنال", "النرويج", "🇳🇴", "MID", 87, 90],
  ["kimmich", "يوشوا كيميش", "بايرن ميونخ", "ألمانيا", "🇩🇪", "MID", 88, 60],
  ["modric", "لوكا مودريتش", "ميلان", "كرواتيا", "🇭🇷", "MID", 86, 20],
  ["fdj", "فرينكي دي يونغ", "برشلونة", "هولندا", "🇳🇱", "MID", 87, 70],
  ["bruno", "برونو فيرنانديز", "مانشستر يونايتد", "البرتغال", "🇵🇹", "MID", 88, 65],
  ["saka", "بوكايو ساكا", "أرسنال", "إنجلترا", "🏴", "WING", 89, 140],
  ["foden", "فيل فودين", "مانشستر سيتي", "إنجلترا", "🏴", "WING", 88, 130],
  ["rapha", "رافينيا", "برشلونة", "البرازيل", "🇧🇷", "WING", 89, 100],
  ["yamal", "لامين يامال", "برشلونة", "إسبانيا", "🇪🇸", "WING", 91, 200],
  ["leao", "رافاييل لياو", "ميلان", "البرتغال", "🇵🇹", "WING", 86, 80],
  ["kvara", "خفيتشا كفاراتسخيليا", "باريس سان جيرمان", "جورجيا", "🇬🇪", "WING", 87, 90],
  ["doku", "جيريمي دوكو", "مانشستر سيتي", "بلجيكا", "🇧🇪", "WING", 84, 70],
  ["nico", "نيكو ويليامز", "أتلتيك بلباو", "إسبانيا", "🇪🇸", "WING", 85, 75],
  ["olise", "مايكل أوليسي", "بايرن ميونخ", "فرنسا", "🇫🇷", "WING", 86, 85],
  ["dembele", "عثمان ديمبيلي", "باريس سان جيرمان", "فرنسا", "🇫🇷", "WING", 88, 90],
  ["griez", "أنطوان غريزمان", "أتلتيكو مدريد", "فرنسا", "🇫🇷", "ST", 86, 30],
  ["osimhen", "فيكتور أوسيمين", "غلطة سراي", "نيجيريا", "🇳🇬", "ST", 88, 75],
  ["vlahovic", "دوسان فلاهوفيتش", "يوفنتوس", "صربيا", "🇷🇸", "ST", 84, 50],
  ["gyokeres", "فيكتور جيوكيريس", "أرسنال", "السويد", "🇸🇪", "ST", 87, 80],
  ["isak", "ألكسندر إيزاك", "ليفربول", "السويد", "🇸🇪", "ST", 87, 110],
  ["martinez_l", "لاوتارو مارتينيز", "إنتر ميلان", "الأرجنتين", "🇦🇷", "ST", 88, 95],
  ["nunez", "دارون نونيز", "الهلال", "أوروغواي", "🇺🇾", "ST", 82, 40],
  ["benzema", "كريم بنزيما", "الاتحاد", "فرنسا", "🇫🇷", "ST", 86, 25],
  ["mitrovic", "ألكسندر ميتروفيتش", "الهلال", "صربيا", "🇷🇸", "ST", 82, 25],
  ["vandijk", "فيرجيل فان دايك", "ليفربول", "هولندا", "🇳🇱", "DEF", 89, 40],
  ["dias", "روبن دياش", "مانشستر سيتي", "البرتغال", "🇵🇹", "DEF", 88, 70],
  ["saliba", "ويليام ساليبا", "أرسنال", "فرنسا", "🇫🇷", "DEF", 88, 90],
  ["hernandez", "تيو هيرنانديز", "الهلال", "فرنسا", "🇫🇷", "DEF", 84, 30],
  ["bastoni", "أليساندرو باستوني", "إنتر ميلان", "إيطاليا", "🇮🇹", "DEF", 86, 70],
  ["hakimi", "أشرف حكيمي", "باريس سان جيرمان", "المغرب", "🇲🇦", "DEF", 87, 70],
  ["cubarsi", "باو كوبارسي", "برشلونة", "إسبانيا", "🇪🇸", "DEF", 85, 90],
  ["marquinhos", "ماركينيوس", "باريس سان جيرمان", "البرازيل", "🇧🇷", "DEF", 85, 35],
  ["rudiger", "أنطونيو روديغر", "ريال مدريد", "ألمانيا", "🇩🇪", "DEF", 85, 25],
  ["carvajal", "داني كارفاخال", "ريال مدريد", "إسبانيا", "🇪🇸", "DEF", 85, 20],
  ["taa", "ترينت ألكسندر-أرنولد", "ليفربول", "إنجلترا", "🏴", "DEF", 86, 70],
  ["gvardiol", "يوشكو غفارديول", "مانشستر سيتي", "كرواتيا", "🇭🇷", "DEF", 86, 80],
  ["militao", "إيدير ميليتاو", "ريال مدريد", "البرازيل", "🇧🇷", "DEF", 84, 45],
  ["kounde", "جول كوندي", "برشلونة", "فرنسا", "🇫🇷", "DEF", 85, 60],
  ["romero", "كريستيان روميرو", "توتنهام", "الأرجنتين", "🇦🇷", "DEF", 85, 60],
  ["alba", "جوردي ألبا", "إنتر ميامي", "إسبانيا", "🇪🇸", "DEF", 79, 8],
  ["courtois", "تيبو كورتوا", "ريال مدريد", "بلجيكا", "🇧🇪", "GK", 89, 35],
  ["alisson", "أليسون بيكر", "ليفربول", "البرازيل", "🇧🇷", "GK", 88, 30],
  ["donnarumma", "جيانلويجي دوناروما", "مانشستر سيتي", "إيطاليا", "🇮🇹", "GK", 88, 45],
  ["terstegen", "مارك تير شتيغن", "برشلونة", "ألمانيا", "🇩🇪", "GK", 87, 30],
  ["neuer", "مانويل نوير", "بايرن ميونخ", "ألمانيا", "🇩🇪", "GK", 86, 12],
  ["maignan", "مايك مينيان", "ميلان", "فرنسا", "🇫🇷", "GK", 86, 35],
  ["raya", "دافيد رايا", "أرسنال", "إسبانيا", "🇪🇸", "GK", 85, 35],
  ["oblak", "يان أوبلاك", "أتلتيكو مدريد", "سلوفينيا", "🇸🇮", "GK", 86, 30],
  ["bounou", "ياسين بونو", "الهلال", "المغرب", "🇲🇦", "GK", 83, 15],
  ["elshenawy", "محمد الشناوي", "الأهلي", "مصر", "🇪🇬", "GK", 79, 5],
  // ── الأساطير الذهبية الخارقة (TITAN LEGENDS - 98 to 100 OVR) ──
  ["pele", "بيليه", "سانتوس", "البرازيل", "🇧🇷", "ST", 100, 150],
  ["maradona", "دييغو مارادونا", "نابولي", "الأرجنتين", "🇦🇷", "MID", 99, 140],
  ["r9", "رونالدو الظاهرة", "إنتر ميلان", "البرازيل", "🇧🇷", "ST", 99, 140],
  ["zidane", "زين الدين زيدان", "ريال مدريد", "فرنسا", "🇫🇷", "MID", 99, 140],
  ["ronaldinho", "رونالدينيو", "برشلونة", "البرازيل", "🇧🇷", "WING", 99, 140],
  ["cruyff", "يوهان كرويف", "أياكس", "هولندا", "🇳🇱", "ST", 99, 135],
  ["beckenbauer", "فرانتز بكنباور", "بايرن ميونخ", "ألمانيا", "🇩🇪", "DEF", 99, 135],
  ["maldini", "باولو مالديني", "ميلان", "إيطاليا", "🇮🇹", "DEF", 99, 135],
  ["cannavaro", "فابيو كانافارو", "يوفنتوس", "إيطاليا", "🇮🇹", "DEF", 98, 120],
  ["buffon", "جيانلويجي بوفون", "يوفنتوس", "إيطاليا", "🇮🇹", "GK", 98, 110],
  ["kahn", "أوليفر كان", "بايرن ميونخ", "ألمانيا", "🇩🇪", "GK", 98, 110],
  ["yashin", "ليف ياشين", "دينامو موسكو", "روسيا", "🇷🇺", "GK", 98, 115],
  ["casillas", "إيكر كاسياس", "ريال مدريد", "إسبانيا", "🇪🇸", "GK", 98, 110],
  ["schmeichel", "بيتر شمايكل", "مانشستر يونايتد", "الدنمارك", "🇩🇰", "GK", 98, 110],
  ["nesta", "أليساندرو نيستا", "ميلان", "إيطاليا", "🇮🇹", "DEF", 98, 115],
  ["roberto_carlos", "روبرتو كارلوس", "ريال مدريد", "البرازيل", "🇧🇷", "DEF", 98, 120],
  ["puyol", "كارليس بويول", "برشلونة", "إسبانيا", "🇪🇸", "DEF", 98, 110],
  ["ramos", "سيرخيو راموس", "ريال مدريد", "إسبانيا", "🇪🇸", "DEF", 98, 110],
  ["iniesta", "أندريس إنييستا", "برشلونة", "إسبانيا", "🇪🇸", "MID", 98, 120],
  ["xavi", "تشافي هيرنانديز", "برشلونة", "إسبانيا", "🇪🇸", "MID", 98, 120],
  ["pirlo", "أندريا بيرلو", "يوفنتوس", "إيطاليا", "🇮🇹", "MID", 98, 120],
  ["gerrard", "ستيفن جيرارد", "ليفربول", "إنجلترا", "🏴", "MID", 98, 115],
  ["scholes", "بول سكولز", "مانشستر يونايتد", "إنجلترا", "🏴", "MID", 98, 115],
  ["beckham", "ديفيد بيكهام", "مانشستر يونايتد", "إنجلترا", "🏴", "MID", 98, 115],
  ["kaka", "كاكا", "ميلان", "البرازيل", "🇧🇷", "MID", 98, 120],
  ["zico", "زيكو", "فلامنغو", "البرازيل", "🇧🇷", "MID", 98, 120],
  ["baggio", "روبرتو باجيو", "يوفنتوس", "إيطاليا", "🇮🇹", "MID", 98, 120],
  ["nedved", "بافيل نيدفيد", "يوفنتوس", "التشيك", "🇨🇿", "MID", 98, 110],
  ["figo", "لويس فيغو", "ريال مدريد", "البرتغال", "🇵🇹", "WING", 98, 115],
  ["puskas", "فيرينتس بوشكاش", "ريال مدريد", "المجر", "🇭🇺", "ST", 98, 125],
  ["eusebio", "أوزيبيو", "بنفيكا", "البرتغال", "🇵🇹", "ST", 98, 125],
  ["romario", "روماريو", "برشلونة", "البرازيل", "🇧🇷", "ST", 98, 125],
  ["henry", "تييري هنري", "أرسنال", "فرنسا", "🇫🇷", "ST", 98, 125],
  ["drogba", "ديدييه دروغبا", "تشيلسي", "ساحل العاج", "🇨🇮", "ST", 98, 115],
  ["totti", "فرانشيسكو توتي", "روما", "إيطاليا", "🇮🇹", "ST", 98, 115],
  ["shevchenko", "أندريه شيفتشينكو", "ميلان", "أوكرانيا", "🇺🇦", "ST", 98, 115],
  ["raul", "راؤول غونزاليس", "ريال مدريد", "إسبانيا", "🇪🇸", "ST", 98, 115],
  ["ibra", "زلاتان إبراهيموفيتش", "ميلان", "السويد", "🇸🇪", "ST", 98, 115],
  ["aguero", "سيرخيو أغويرو", "مانشستر سيتي", "الأرجنتين", "🇦🇷", "ST", 98, 110],
  ["robben", "أريين روبن", "بايرن ميونخ", "هولندا", "🇳🇱", "WING", 98, 115],
  ["ribery", "فرانك ريبيري", "بايرن ميونخ", "فرنسا", "🇫🇷", "WING", 98, 115],
  ["bale", "غاريث بيل", "ريال مدريد", "ويلز", "🏴", "WING", 98, 115],
  ["hazard", "إيدين هازارد", "تشيلسي", "بلجيكا", "🇧🇪", "WING", 98, 110],
  ["neymar", "نيمار جونيور", "سانتوس", "البرازيل", "🇧🇷", "WING", 97, 85],
  // weaker / filler
  ["abolamba", "أبو لمبة", "فريق الحارة", "مجهول", "🏳️", "ST", 45, 1],
  ["hares", "حارس الحارة", "فريق الحارة", "مجهول", "🏳️", "GK", 48, 1],
  ["saadoun", "سعدون الدفاع", "فريق الحارة", "مجهول", "🏳️", "DEF", 50, 1],
  ["fahd", "فهد الوسط", "فريق الحارة", "مجهول", "🏳️", "MID", 52, 1],
  ["waleed", "وليد الجناح", "فريق الحارة", "مجهول", "🏳️", "WING", 51, 1],
  ["rookie_gk", "عمر السيد", "نادي الشباب", "السعودية", "🇸🇦", "GK", 72, 4],
  ["rookie_def", "علي البليهي", "الهلال", "السعودية", "🇸🇦", "DEF", 74, 5],
  ["rookie_mid", "سالم الدوسري", "الهلال", "السعودية", "🇸🇦", "MID", 82, 20],
  ["rookie_wing", "رياض محرز", "الأهلي", "الجزائر", "🇩🇿", "WING", 83, 20],
  ["rookie_st", "فراس البريكان", "الأهلي", "السعودية", "🇸🇦", "ST", 76, 8],
  ["akram", "أكرم عفيف", "السد", "قطر", "🇶🇦", "WING", 79, 10],
  ["moanes", "مؤنس دبور", "هوفنهايم", "تونس", "🇹🇳", "ST", 77, 9],
  ["hakim", "حكيم زياش", "الدحيل", "المغرب", "🇲🇦", "WING", 80, 12],
  ["amrabat", "سفيان أمرابط", "فنربخشة", "المغرب", "🇲🇦", "MID", 79, 12],
  ["elneny", "محمد النني", "جدة", "مصر", "🇪🇬", "MID", 74, 4],
  ["hegazy", "أحمد حجازي", "الاتحاد", "مصر", "🇪🇬", "DEF", 76, 5],
  ["marcelo", "مارسيلو", "فلومينينسي", "البرازيل", "🇧🇷", "DEF", 80, 6],
  ["dani", "داني ألفيش", "برشلونة", "البرازيل", "🇧🇷", "DEF", 82, 6],
  // ===== نجوم حاليون إضافيون =====
  ["palmer", "كول بالمر", "تشيلسي", "إنجلترا", "🏴", "MID", 87, 110],
  ["rice", "ديكلان رايس", "أرسنال", "إنجلترا", "🏴", "MID", 87, 100],
  ["mainoo", "كوبي ماينو", "مانشستر يونايتد", "إنجلترا", "🏴", "MID", 82, 55],
  ["zubimendi", "مارتن زوبيميندي", "أرسنال", "إسبانيا", "🇪🇸", "MID", 85, 65],
  ["tchouameni", "أوريلين تشواميني", "ريال مدريد", "فرنسا", "🇫🇷", "MID", 86, 80],
  ["camavinga", "إدواردو كامافينغا", "ريال مدريد", "فرنسا", "🇫🇷", "MID", 85, 80],
  ["barella", "نيكولو باريلا", "إنتر ميلان", "إيطاليا", "🇮🇹", "MID", 86, 70],
  ["szoboszlai", "دومينيك سوبوسلاي", "ليفربول", "المجر", "🇭🇺", "MID", 85, 70],
  ["mac_allister", "أليكسيس ماك أليستر", "ليفربول", "الأرجنتين", "🇦🇷", "MID", 86, 75],
  ["konate", "إبراهيما كوناتي", "ليفربول", "فرنسا", "🇫🇷", "DEF", 84, 50],
  ["martinez_e", "إيميليانو مارتينيز", "أستون فيلا", "الأرجنتين", "🇦🇷", "GK", 85, 25],
  ["sommer", "يان سومر", "إنتر ميلان", "سويسرا", "🇨🇭", "GK", 84, 10],
  ["diogo", "ديوغو كوستا", "بورتو", "البرتغال", "🇵🇹", "GK", 85, 45],
  ["saliba2", "ليني يورو", "مانشستر يونايتد", "فرنسا", "🇫🇷", "DEF", 81, 45],
  ["huijsen", "دين هاوسن", "ريال مدريد", "إسبانيا", "🇪🇸", "DEF", 83, 60],
  ["guehi", "مارك غيهي", "ليفربول", "إنجلترا", "🏴", "DEF", 84, 45],
  ["dumfries", "دينزل دومفريز", "إنتر ميلان", "هولندا", "🇳🇱", "DEF", 84, 40],
  ["theo2", "أليخاندرو غراندي", "أتلتيكو مدريد", "إسبانيا", "🇪🇸", "DEF", 79, 15],
  ["sesko", "بنجامين شيشكو", "مانشستر يونايتد", "سلوفينيا", "🇸🇮", "ST", 84, 75],
  ["zirkzee", "يوشوا زيركزي", "مانشستر يونايتد", "هولندا", "🇳🇱", "ST", 80, 35],
  ["retegui", "ماتيو ريتيغي", "أتالانتا", "إيطاليا", "🇮🇹", "ST", 84, 45],
  ["david", "جوناثان ديفيد", "يوفنتوس", "كندا", "🇨🇦", "ST", 84, 40],
  ["openda", "لويس أوبندا", "يوفنتوس", "بلجيكا", "🇧🇪", "ST", 83, 40],
  ["marmoush", "عمر مرموش", "مانشستر سيتي", "مصر", "🇪🇬", "ST", 84, 60],
  ["kudus", "محمد كودوس", "توتنهام", "غانا", "🇬🇭", "WING", 83, 45],
  ["mudryk", "ميخايلو مودريك", "تشيلسي", "أوكرانيا", "🇺🇦", "WING", 79, 25],
  ["garnacho", "أليخاندرو غارناتشو", "تشيلسي", "الأرجنتين", "🇦🇷", "WING", 82, 45],
  ["rodrygo", "رودريغو غويس", "ريال مدريد", "البرازيل", "🇧🇷", "WING", 87, 90],
  ["cherki", "رايان شرقي", "مانشستر سيتي", "فرنسا", "🇫🇷", "WING", 84, 55],
  ["diaz_l", "لويس دياز", "بايرن ميونخ", "كولومبيا", "🇨🇴", "WING", 85, 60],
  ["nkunku", "كريستوفر نكونكو", "ميلان", "فرنسا", "🇫🇷", "ST", 83, 35],
  // ===== نجوم عرب =====
  ["hamdallah", "عبد الرزاق حمد الله", "الشباب", "المغرب", "🇲🇦", "ST", 79, 8],
  ["kanno", "محمد كنو", "الهلال", "السعودية", "🇸🇦", "MID", 78, 8],
  ["alshehri", "صالح الشهري", "الأهلي", "السعودية", "🇸🇦", "ST", 77, 7],
  ["trezeguet", "محمود تريزيغيه", "الأهلي", "مصر", "🇪🇬", "WING", 78, 8],
  ["mostafa", "مصطفى محمد", "نانت", "مصر", "🇪🇬", "ST", 77, 10],
  ["msakni", "يوسف المساكني", "الدحيل", "تونس", "🇹🇳", "WING", 76, 5],
  ["bennasser", "نادر غندري", "الترجي", "تونس", "🇹🇳", "DEF", 74, 4],
  ["bouali", "يوسف بلعيد", "الترجي", "الجزائر", "🇩🇿", "DEF", 75, 5],
  ["elsulaya", "علي لاجامي", "النصر", "السعودية", "🇸🇦", "DEF", 75, 5],
  ["alowais", "نواف العقيدي", "النصر", "السعودية", "🇸🇦", "GK", 76, 6],
  ["hamed", "محمد عواد", "الزمالك", "مصر", "🇪🇬", "GK", 74, 3],
  // ===== دفعة عالمية إضافية =====
  ["ederson", "إيدرسون", "مانشستر سيتي", "البرازيل", "🇧🇷", "GK", 87, 35],
  ["lunin", "أندري لونين", "ريال مدريد", "أوكرانيا", "🇺🇦", "GK", 83, 25],
  ["onana", "أندريه أونانا", "مانشستر يونايتد", "الكاميرون", "🇨🇲", "GK", 82, 20],
  ["mamardashvili", "جيورجي مامارداشفيلي", "ليفربول", "جورجيا", "🇬🇪", "GK", 84, 35],
  ["vicario", "غولييلمو فيكاريو", "توتنهام", "إيطاليا", "🇮🇹", "GK", 83, 25],
  ["trubin", "أناتولي تروبين", "بنفيكا", "أوكرانيا", "🇺🇦", "GK", 82, 22],
  ["kobel", "غريغور كوبل", "بوروسيا دورتموند", "سويسرا", "🇨🇭", "GK", 86, 40],
  ["nuno_mendes", "نونو مينديش", "باريس سان جيرمان", "البرتغال", "🇵🇹", "DEF", 86, 75],
  ["van_de_ven", "ميكي فان دي فين", "توتنهام", "هولندا", "🇳🇱", "DEF", 84, 55],
  ["araujo", "رونالد أراوخو", "برشلونة", "أوروغواي", "🇺🇾", "DEF", 86, 70],
  ["kim_minjae", "كيم مين جاي", "بايرن ميونخ", "كوريا الجنوبية", "🇰🇷", "DEF", 84, 45],
  ["upamecano", "دايوت أوباميكانو", "بايرن ميونخ", "فرنسا", "🇫🇷", "DEF", 84, 50],
  ["calafiori", "ريكاردو كالافيوري", "أرسنال", "إيطاليا", "🇮🇹", "DEF", 83, 55],
  ["gabriel", "غابرييل ماغالهايس", "أرسنال", "البرازيل", "🇧🇷", "DEF", 87, 75],
  ["stones", "جون ستونز", "مانشستر سيتي", "إنجلترا", "🏴", "DEF", 84, 35],
  ["de_ligt", "ماتياس دي ليخت", "مانشستر يونايتد", "هولندا", "🇳🇱", "DEF", 84, 45],
  ["bremer", "غليسون بريمر", "يوفنتوس", "البرازيل", "🇧🇷", "DEF", 85, 55],
  ["dimarco", "فيديريكو ديماركو", "إنتر ميلان", "إيطاليا", "🇮🇹", "DEF", 85, 50],
  ["frattesi", "دافيدي فراتيسي", "إنتر ميلان", "إيطاليا", "🇮🇹", "MID", 83, 45],
  ["vitinha", "فيتينيا", "باريس سان جيرمان", "البرتغال", "🇵🇹", "MID", 88, 95],
  ["joao_neves", "جواو نيفيش", "باريس سان جيرمان", "البرتغال", "🇵🇹", "MID", 86, 90],
  ["enzo", "إنزو فرنانديز", "تشيلسي", "الأرجنتين", "🇦🇷", "MID", 85, 75],
  ["caicedo", "مويسيس كايسيدو", "تشيلسي", "الإكوادور", "🇪🇨", "MID", 86, 85],
  ["bernardo", "برناردو سيلفا", "مانشستر سيتي", "البرتغال", "🇵🇹", "MID", 88, 65],
  ["gundogan", "إلكاي غوندوغان", "مانشستر سيتي", "ألمانيا", "🇩🇪", "MID", 85, 25],
  ["locatelli", "مانويل لوكاتيلي", "يوفنتوس", "إيطاليا", "🇮🇹", "MID", 84, 40],
  ["depaul", "رودريغو دي بول", "أتلتيكو مدريد", "الأرجنتين", "🇦🇷", "MID", 84, 40],
  ["xavi_simons", "تشافي سيمونز", "لايبزيغ", "هولندا", "🇳🇱", "MID", 85, 75],
  ["doue", "ديزيري دوي", "باريس سان جيرمان", "فرنسا", "🇫🇷", "WING", 86, 90],
  ["barcola", "برادلي باركولا", "باريس سان جيرمان", "فرنسا", "🇫🇷", "WING", 85, 80],
  ["kubo", "تاكيفوسا كوبو", "ريال سوسيداد", "اليابان", "🇯🇵", "WING", 84, 60],
  ["mitoma", "كاورو ميتوما", "برايتون", "اليابان", "🇯🇵", "WING", 83, 50],
  ["sancho", "جادون سانشو", "مانشستر يونايتد", "إنجلترا", "🏴", "WING", 82, 35],
  ["coman", "كينغسلي كومان", "بايرن ميونخ", "فرنسا", "🇫🇷", "WING", 84, 40],
  ["chiesa", "فيديريكو كييزا", "ليفربول", "إيطاليا", "🇮🇹", "WING", 83, 35],
  ["savinho", "سافينيو", "مانشستر سيتي", "البرازيل", "🇧🇷", "WING", 83, 60],
  ["julian", "جوليان ألفاريز", "أتلتيكو مدريد", "الأرجنتين", "🇦🇷", "ST", 88, 100],
  ["thuram", "ماركوس تورام", "إنتر ميلان", "فرنسا", "🇫🇷", "ST", 86, 65],
  ["hojlund", "راسموس هويلوند", "مانشستر يونايتد", "الدنمارك", "🇩🇰", "ST", 82, 55],
  ["boniface", "فيكتور بونيفيس", "باير ليفركوزن", "نيجيريا", "🇳🇬", "ST", 84, 50],
  ["watkins", "أولي واتكينز", "أستون فيلا", "إنجلترا", "🏴", "ST", 85, 55],
  ["solanke", "دومينيك سولانكي", "توتنهام", "إنجلترا", "🏴", "ST", 83, 45],
  ["endrick", "إندريك", "ريال مدريد", "البرازيل", "🇧🇷", "ST", 80, 55],
  ["duran", "جون دوران", "النصر", "كولومبيا", "🇨🇴", "ST", 82, 45],
  // ===== كروت ضعيفة (بدائل) =====
  ["hamada", "حمادة الجزار", "فريق الحارة", "مجهول", "🏳️", "MID", 47, 1],
  ["sobhy", "صبحي المرمى", "فريق الحارة", "مجهول", "🏳️", "GK", 44, 1],
  ["taha", "طه الظهير", "فريق الحارة", "مجهول", "🏳️", "DEF", 46, 1],
  ["nabil", "نبيل السريع", "فريق الحارة", "مجهول", "🏳️", "WING", 49, 1],
  ["ashraf", "أشرف الهداف", "فريق الحارة", "مجهول", "🏳️", "ST", 50, 1],
  ["reserve_gk", "بدر الحارس", "نادي الشباب", "السعودية", "🇸🇦", "GK", 68, 2],
  ["reserve_def", "خالد الصلب", "نادي الشباب", "السعودية", "🇸🇦", "DEF", 66, 2],
  ["reserve_mid", "ماجد المحرك", "نادي الشباب", "السعودية", "🇸🇦", "MID", 67, 2],
  ["reserve_wing", "طلال البرق", "نادي الشباب", "السعودية", "🇸🇦", "WING", 65, 2],
  ["reserve_st", "بسام الرأس", "نادي الشباب", "السعودية", "🇸🇦", "ST", 64, 2],
];

export const PLAYERS: Player[] = ROWS.map(
  ([id, nameAr, clubAr, nation, flag, base, overall, value]) => {
    const imgUrl = PLAYER_IMAGES[id];
    return {
      id,
      nameAr,
      clubAr,
      nation,
      flag,
      league: leagueOf(clubAr),
      base,
      overall,
      value,
      tier: tierOf(overall),
      ...(imgUrl ? { image: imgUrl } : {}),
    };
  },
);

function leagueOf(club: string): string {
  const map: Record<string, string> = {
    "ريال مدريد": "الليغا",
    برشلونة: "الليغا",
    "أتلتيكو مدريد": "الليغا",
    "أتلتيك بلباو": "الليغا",
    ليفربول: "البريميرليغ",
    "مانشستر سيتي": "البريميرليغ",
    أرسنال: "البريميرليغ",
    "مانشستر يونايتد": "البريميرليغ",
    توتنهام: "البريميرليغ",
    تشيلسي: "البريميرليغ",
    "بايرن ميونخ": "البوندسليغا",
    هوفنهايم: "البوندسليغا",
    ميلان: "الكالتشيو",
    "إنتر ميلان": "الكالتشيو",
    يوفنتوس: "الكالتشيو",
    نابولي: "الكالتشيو",
    "باريس سان جيرمان": "الليغ 1",
    الهلال: "دوري روشن",
    النصر: "دوري روشن",
    الاتحاد: "دوري روشن",
    "الأهلي": "دوري روشن",
    "نادي الشباب": "دوري روشن",
    الشباب: "دوري روشن",
    أياكس: "دوري عالمي",
    بنفيكا: "دوري عالمي",
    بورتو: "دوري عالمي",
    فلامنغو: "دوري عالمي",
    سانتوس: "دوري عالمي",
    روما: "الكالتشيو",
    أتالانتا: "الكالتشيو",
    "أستون فيلا": "البريميرليغ",
    نانت: "الليغ 1",
    الترجي: "دوري عالمي",
    الدحيل: "دوري عالمي",
    السد: "دوري عالمي",
    الزمالك: "الدوري المصري",
    جدة: "دوري روشن",
    "دينامو موسكو": "دوري عالمي",
    فنربخشة: "دوري عالمي",
    "غلطة سراي": "دوري عالمي",
    فلومينينسي: "دوري عالمي",
    "إنتر ميامي": "الدوري الأمريكي",
  };
  return map[club] ?? "دوري عالمي";
}

export const POSITIONS_5: { key: string; base: BasePos; label: string }[] = [
  { key: "GK", base: "GK", label: "حارس مرمى" },
  { key: "DEF", base: "DEF", label: "مدافع" },
  { key: "MID", base: "MID", label: "وسط" },
  { key: "WING", base: "WING", label: "جناح" },
  { key: "ST", base: "ST", label: "مهاجم" },
];

export const POSITIONS_11: { key: string; base: BasePos; label: string }[] = [
  { key: "GK", base: "GK", label: "حارس مرمى" },
  { key: "LB", base: "DEF", label: "ظهير أيسر" },
  { key: "LCB", base: "DEF", label: "قلب دفاع أيسر" },
  { key: "RCB", base: "DEF", label: "قلب دفاع أيمن" },
  { key: "RB", base: "DEF", label: "ظهير أيمن" },
  { key: "LM", base: "MID", label: "وسط أيسر" },
  { key: "CM", base: "MID", label: "وسط مرتكز" },
  { key: "RM", base: "MID", label: "وسط أيمن" },
  { key: "LW", base: "WING", label: "جناح أيسر" },
  { key: "ST", base: "ST", label: "مهاجم صريح" },
  { key: "RW", base: "WING", label: "جناح أيمن" },
];

export function positionsFor(mode: string) {
  return mode === "11" ? POSITIONS_11 : POSITIONS_5;
}

// x/y as percentage of own half (y: 0 = own goal line, 100 = halfway)
export const LAYOUT_5: Record<string, { x: number; y: number }> = {
  GK: { x: 50, y: 8 },
  DEF: { x: 50, y: 32 },
  MID: { x: 50, y: 55 },
  WING: { x: 22, y: 72 },
  ST: { x: 68, y: 85 },
};

export const LAYOUT_11: Record<string, { x: number; y: number }> = {
  GK: { x: 50, y: 7 },
  LB: { x: 15, y: 26 },
  LCB: { x: 38, y: 20 },
  RCB: { x: 62, y: 20 },
  RB: { x: 85, y: 26 },
  LM: { x: 25, y: 50 },
  CM: { x: 50, y: 46 },
  RM: { x: 75, y: 50 },
  LW: { x: 18, y: 76 },
  ST: { x: 50, y: 86 },
  RW: { x: 82, y: 76 },
};

export function layoutFor(mode: string) {
  return mode === "11" ? LAYOUT_11 : LAYOUT_5;
}

export function shirtNumber(posKey: string): number {
  const map: Record<string, number> = {
    GK: 1,
    LB: 3,
    LCB: 4,
    RCB: 5,
    RB: 2,
    LM: 8,
    CM: 6,
    RM: 7,
    LW: 11,
    ST: 9,
    RW: 10,
    DEF: 4,
    MID: 8,
    WING: 11,
  };
  return map[posKey] ?? 12;
}

// ===== الخطط التكتيكية =====
export type Tactic = "attack" | "balanced" | "defend";

export const TACTICS: { id: Tactic; label: string; icon: string; desc: string }[] = [
  { id: "attack", label: "هجومي", icon: "⚔️", desc: "قوة هجوم أعلى لكن الدفاع مكشوف" },
  { id: "balanced", label: "متوازن", icon: "⚖️", desc: "توازن بين الهجوم والدفاع" },
  { id: "defend", label: "دفاعي", icon: "🛡️", desc: "دفاع صخري مع هجمات مرتدة" },
];

// ===== أساليب اللعب =====
export type PlayStyle =
  | "counter"      // المرتدة
  | "long_ball"    // الكرة الطويلة
  | "possession"   // الاستحواذ
  | "crosses"      // العرضيات
  | "longshots";   // الشوت من بره 18

export interface PlayStyleMeta {
  id: PlayStyle;
  label: string;
  icon: string;
  desc: string;
  /** تأثير على نسبة الاستحواذ (+/- نقطة) */
  possessionMod: number;
  /** معامل ضرب الهجوم */
  attMul: number;
  /** معامل ضرب الدفاع */
  defMul: number;
  /** احتمال إضافي للفرص (0-1) */
  chanceMod: number;
  /** تضخيم قوة الجناح WING (معامل) */
  wingMul: number;
  /** احتمال هدف صاروخي من بعيد كل دقيقة */
  longshotChance: number;
}

export const PLAY_STYLES: PlayStyleMeta[] = [
  {
    id: "counter",
    label: "المرتدة",
    icon: "⚡",
    desc: "هجمات مرتدة خاطفة — هجوم أعلى +15% لكن استحواذ أقل",
    possessionMod: -8,
    attMul: 1.15,
    defMul: 1.0,
    chanceMod: 0.02,
    wingMul: 1.0,
    longshotChance: 0,
  },
  {
    id: "long_ball",
    label: "كرة طويلة",
    icon: "📏",
    desc: "كرات عمق مباشرة — فرص هجوم أكثر بدون استحواذ عالٍ",
    possessionMod: -5,
    attMul: 1.08,
    defMul: 0.95,
    chanceMod: 0.04,
    wingMul: 1.0,
    longshotChance: 0,
  },
  {
    id: "possession",
    label: "الاستحواذ",
    icon: "🔄",
    desc: "تمرير مستمر وضغط — استحواذ +12% وتقليل فرص الخصم",
    possessionMod: 12,
    attMul: 0.97,
    defMul: 1.05,
    chanceMod: -0.03,
    wingMul: 1.0,
    longshotChance: 0,
  },
  {
    id: "crosses",
    label: "العرضيات",
    icon: "🤸",
    desc: "الاعتماد على الأجنحة — لاعبو الجناح يزداد تأثيرهم +8%",
    possessionMod: 2,
    attMul: 1.0,
    defMul: 1.0,
    chanceMod: 0.01,
    wingMul: 1.08,
    longshotChance: 0,
  },
  {
    id: "longshots",
    label: "شوت من بره 18",
    icon: "💥",
    desc: "تسديد من خارج منطقة الجزاء — فرصة هدف صاروخي عشوائي",
    possessionMod: 0,
    attMul: 1.0,
    defMul: 1.0,
    chanceMod: 0,
    wingMul: 1.0,
    longshotChance: 0.025,
  },
];

export interface FormationPreset {
  id: string;
  label: string;
  spots: Record<string, { x: number; y: number }>;
}

export const FORMATIONS_5: FormationPreset[] = [
  {
    id: "1-2-1",
    label: "1-2-1 متوازن",
    spots: { GK: { x: 50, y: 8 }, DEF: { x: 50, y: 32 }, MID: { x: 50, y: 55 }, WING: { x: 22, y: 72 }, ST: { x: 68, y: 85 } },
  },
  {
    id: "2-1-1",
    label: "2-1-1 دفاعي",
    spots: { GK: { x: 50, y: 7 }, DEF: { x: 34, y: 26 }, MID: { x: 66, y: 30 }, WING: { x: 30, y: 60 }, ST: { x: 60, y: 82 } },
  },
  {
    id: "1-1-2",
    label: "1-1-2 هجومي",
    spots: { GK: { x: 50, y: 7 }, DEF: { x: 50, y: 26 }, MID: { x: 50, y: 48 }, WING: { x: 24, y: 84 }, ST: { x: 70, y: 90 } },
  },
  {
    id: "1-2-2",
    label: "1-2-2 ضغط هجومي",
    spots: { GK: { x: 50, y: 7 }, DEF: { x: 50, y: 28 }, MID: { x: 28, y: 55 }, WING: { x: 72, y: 55 }, ST: { x: 50, y: 88 } },
  },
];

export const FORMATIONS_11: FormationPreset[] = [
  {
    id: "4-3-3",
    label: "4-3-3",
    spots: {
      GK: { x: 50, y: 7 }, LB: { x: 15, y: 26 }, LCB: { x: 38, y: 20 }, RCB: { x: 62, y: 20 }, RB: { x: 85, y: 26 },
      LM: { x: 25, y: 50 }, CM: { x: 50, y: 46 }, RM: { x: 75, y: 50 },
      LW: { x: 18, y: 76 }, ST: { x: 50, y: 86 }, RW: { x: 82, y: 76 },
    },
  },
  {
    id: "4-4-2",
    label: "4-4-2",
    spots: {
      GK: { x: 50, y: 7 }, LB: { x: 14, y: 24 }, LCB: { x: 38, y: 18 }, RCB: { x: 62, y: 18 }, RB: { x: 86, y: 24 },
      LM: { x: 22, y: 52 }, CM: { x: 44, y: 48 }, RM: { x: 66, y: 52 },
      LW: { x: 20, y: 72 }, ST: { x: 44, y: 88 }, RW: { x: 74, y: 88 },
    },
  },
  {
    id: "3-5-2",
    label: "3-5-2",
    spots: {
      GK: { x: 50, y: 7 }, LB: { x: 26, y: 20 }, LCB: { x: 50, y: 16 }, RCB: { x: 74, y: 20 }, RB: { x: 88, y: 44 },
      LM: { x: 14, y: 44 }, CM: { x: 42, y: 46 }, RM: { x: 62, y: 52 },
      LW: { x: 32, y: 70 }, ST: { x: 46, y: 88 }, RW: { x: 72, y: 84 },
    },
  },
  {
    id: "5-3-2",
    label: "5-3-2 دفاعي",
    spots: {
      GK: { x: 50, y: 6 }, LB: { x: 10, y: 22 }, LCB: { x: 32, y: 16 }, RCB: { x: 50, y: 14 }, RB: { x: 68, y: 16 },
      LM: { x: 88, y: 22 }, CM: { x: 34, y: 46 }, RM: { x: 66, y: 46 },
      LW: { x: 50, y: 52 }, ST: { x: 38, y: 84 }, RW: { x: 66, y: 84 },
    },
  },
  {
    id: "4-2-3-1",
    label: "4-2-3-1 هجومي منظّم",
    spots: {
      GK: { x: 50, y: 7 }, LB: { x: 14, y: 22 }, LCB: { x: 38, y: 17 }, RCB: { x: 62, y: 17 }, RB: { x: 86, y: 22 },
      LM: { x: 34, y: 40 }, CM: { x: 66, y: 40 }, RM: { x: 20, y: 62 },
      LW: { x: 50, y: 60 }, ST: { x: 78, y: 62 }, RW: { x: 50, y: 86 },
    },
  },
  {
    id: "3-4-3",
    label: "3-4-3 ضغط عالٍ",
    spots: {
      GK: { x: 50, y: 7 }, LB: { x: 26, y: 21 }, LCB: { x: 50, y: 17 }, RCB: { x: 74, y: 21 }, RB: { x: 88, y: 46 },
      LM: { x: 12, y: 46 }, CM: { x: 40, y: 50 }, RM: { x: 62, y: 50 },
      LW: { x: 20, y: 80 }, ST: { x: 50, y: 88 }, RW: { x: 80, y: 80 },
    },
  },
];

export function formationsFor(mode: string) {
  return mode === "11" ? FORMATIONS_11 : FORMATIONS_5;
}
