/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as TournamentCodeRouteImport } from './routes/tournament.$code'
import { Route as ApiPublicRoomAccessRouteImport } from './routes/api/public/room-access'
import { Route as ApiPublicTournamentAccessRouteImport } from './routes/api/public/tournament-access'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentCodeRoute = TournamentCodeRouteImport.update({
  id: '/tournament/$code',
  path: '/tournament/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRoomAccessRoute = ApiPublicRoomAccessRouteImport.update({
  id: '/api/public/room-access',
  path: '/api/public/room-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTournamentAccessRoute =
  ApiPublicTournamentAccessRouteImport.update({
    id: '/api/public/tournament-access',
    path: '/api/public/tournament-access',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$code': typeof RoomCodeRoute
  '/tournament/$code': typeof TournamentCodeRoute
  '/api/public/room-access': typeof ApiPublicRoomAccessRoute
  '/api/public/tournament-access': typeof ApiPublicTournamentAccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$code': typeof RoomCodeRoute
  '/tournament/$code': typeof TournamentCodeRoute
  '/api/public/room-access': typeof ApiPublicRoomAccessRoute
  '/api/public/tournament-access': typeof ApiPublicTournamentAccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$code': typeof RoomCodeRoute
  '/tournament/$code': typeof TournamentCodeRoute
  '/api/public/room-access': typeof ApiPublicRoomAccessRoute
  '/api/public/tournament-access': typeof ApiPublicTournamentAccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/room/$code'
    | '/tournament/$code'
    | '/api/public/room-access'
    | '/api/public/tournament-access'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/room/$code'
    | '/tournament/$code'
    | '/api/public/room-access'
    | '/api/public/tournament-access'
  id:
    | '__root__'
    | '/'
    | '/room/$code'
    | '/tournament/$code'
    | '/api/public/room-access'
    | '/api/public/tournament-access'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomCodeRoute: typeof RoomCodeRoute
  TournamentCodeRoute: typeof TournamentCodeRoute
  ApiPublicRoomAccessRoute: typeof ApiPublicRoomAccessRoute
  ApiPublicTournamentAccessRoute: typeof ApiPublicTournamentAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$code': {
      id: '/tournament/$code'
      path: '/tournament/$code'
      fullPath: '/tournament/$code'
      preLoaderRoute: typeof TournamentCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/room-access': {
      id: '/api/public/room-access'
      path: '/api/public/room-access'
      fullPath: '/api/public/room-access'
      preLoaderRoute: typeof ApiPublicRoomAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tournament-access': {
      id: '/api/public/tournament-access'
      path: '/api/public/tournament-access'
      fullPath: '/api/public/tournament-access'
      preLoaderRoute: typeof ApiPublicTournamentAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomCodeRoute: RoomCodeRoute,
  TournamentCodeRoute: TournamentCodeRoute,
  ApiPublicRoomAccessRoute: ApiPublicRoomAccessRoute,
  ApiPublicTournamentAccessRoute: ApiPublicTournamentAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
